#!/usr/bin/env bash

# =========================================
# HELP
# =========================================
printHelp () {
  cat <<HELPPAGE
  Description:
    A simple trash script written in bash.

  Usage: utrash [ACTION] [SCOPE] [DATE] [EXTRA]
         utrash [FILE(S)]

  Action:
    -h, --help
      Print this help page.

    -e, --empty
      Empty the trash.

    -l, --list
      List trashed items.

    -r, --restore
      Restore item(s) to their original path.

  Scope:
    -d, --here
      Operate on this directory recursively.

    -D, --here-only
      Operate on this directory only (non recursive).

  Date:
    -t, --today
      Items trashed today.

    -p, --yesterday
      Items trashed yesterday.

    -m, --month
      Items trashed this month.

    -y, --year
      Items trashed this year.

  Extra:
    -c, --custom
      Use a custom restore directory instead of
      original directory.

    -nf, --no-fzf
      Print instead of using fzf.

  Examples:
    1. utrash hello
        Trashes 'hello' file.

    2. utrash file1 file2 dir1
        Trashes file1, file2 and dir1.

    3. utrash *
        Trashes all files and directories 
        in the current directory.

    4. utrash -r 
        Select item(s) to recover using fzf.
HELPPAGE
}

# Check help option and print help page then exit.
if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]] || [[ "${@: -1}" == "-h" ]] || [[ "${@: -1}" == "--help" ]]; then
  printHelp
  exit
fi

# =========================================
# DIRECTORIES
# =========================================
checkDir () {
  if [[ ! -d "$1" ]]; then
    mkdir -p "$1"
  fi
}

TRASH_DIR="$HOME/.local/share/utrash"

checkDir "$TRASH_DIR"

# =========================================
# FUNCTIONS
# =========================================
empty () {
  read -rp "Are you sure you want to delete EVERYTHING in the trash? (y/N) " asked
  if [[ "$asked" == "y" ]]; then
    rm -rf "$TRASH_DIR"/*
    echo "Trash cleaned"
  else
    echo "Nothing in the trash was deleted"
  fi
}

absolutePath () {
  targetName="$1"
  dirName="`dirname "$2"`"
  echo "`cd "$dirName"; pwd`/$targetName"
}

fzfCmd () {
  fzfBindings=(
    "tab:toggle+up"
    "shift-tab:toggle+down"
    "ctrl-a:toggle-all"
  )

  allFzfBinds="`echo "${fzfBindings[@]@Q}" |\
    sed "s/^'//g; s/'$//g; s/' '/,/g"`"

  fzf -m \
    --tac \
    --bind="$allFzfBinds" \
    --header="[tab:toggleUp, S-tab:toggleDown, C-a:toggleAll]"
}

# =========================================
# PROCESS ARGUMENTS
# =========================================

case "$1" in
"-e"|"--empty")
  empty
  exit
  ;;

"-r"|"--restore") 
  action="restore" 
  ;;

"-l"|"--list") 
  action="list" 
  ;;

-*)
  echo "ERR: Invalid action"
  printHelp
  exit
  ;;

*)
  if [[ "$#" -gt "0" ]]; then
    checkDir "$TRASH_DIR/$today"
    for target in "${@}"; do
      if [[ -f "$target" ]] || [[ -d "$target" ]]; then
        today="`date "+%d-%m-%Y"`"
        targetName="`basename "$target"`"
        path="`absolutePath "$targetName" "$target"`"
        echo "$today/$targetName:::$path" >> $TRASH_DIR/record
        mv "$path" "$TRASH_DIR/$today"
        echo "Trashed '$targetName'"
      else
        echo "Could not trash '$target' no such file or directory."
      fi
    done
  else
    echo "Please, specify an item to trash."
  fi
  exit
  ;;
esac

shift

while [[ $# > 0 ]]; do
  case "$1" in
    "-d"|"--here") 
      scope="`pwd`"
      recurse=1
      shift
      ;;

    "-D"|"--here-only")
      scope="`pwd`"
      shift
      ;;

    "-t"|"--today") 
      date="`date "+%d-%m-%Y"`"
      shift
      ;;

    "-p"|"--yesterday")
      date="`date -d "-1 day" "+%d-%m-%Y"`"
      shift
      ;;
    
    "-m"|"--month")
      date="`date "+..-%m-%Y"`"
      shift
      ;;

    "-y"|"--year")
      date="`date "+..-..-%Y"`"
      shift
      ;;

    "-nf"|"--no-fzf")
      noFzf=1
      shift
      ;;

    "-c"|"--custom")
      read -rp "Custom directory: " customDir
      shift
      ;;
  esac
done

case "$action" in
  "list")
    if [[ -f "$TRASH_DIR/record" ]]; then
      if [[ -n "$date" ]] && [[ -n "$scope" ]]; then
        if grep -q "^$date/" "$TRASH_DIR/record"; then
          if grep -q ":::`pwd`" "$TRASH_DIR/record"; then
            if [[ $recurse == 1 ]]; then
              cat "$TRASH_DIR/record" |\
                grep "^$date/" |\
                grep ":::`pwd`" |\
                awk -F ":::" '{print $1}' |\
                fzfCmd
            else
              cat "$TRASH_DIR/record" |\
                grep "^$date/" |\
                grep ":::`pwd`/[a-zA-Z0-9]*$" |\
                awk -F ":::" '{print $1}' |\
                fzfCmd
            fi
          else
            echo "Nothing was trashed from here."
          fi
        else
          echo "Nothing was trashed matching date specified."
        fi
      elif [[ -n "$date" ]] && [[ -z "$scope" ]]; then
        if grep -q "^$date/" "$TRASH_DIR/record"; then
          cat "$TRASH_DIR/record" |\
            grep "^$date/" |\
            awk -F ":::" '{print $1}' |\
            fzfCmd
        else
          echo "Nothing was trashed matching date specified."
        fi
      elif [[ -z "$date" ]] && [[ -n "$scope" ]]; then
        if grep -q ":::`pwd`" "$TRASH_DIR/record"; then
          if [[ $recurse == 1 ]]; then
            cat "$TRASH_DIR/record" |\
              grep ":::`pwd`" |\
              awk -F ":::" '{print $1}' |\
              fzfCmd
          else
            cat "$TRASH_DIR/record" |\
              grep ":::`pwd`[a-zA-Z0-9]*$" |\
              awk -F ":::" '{print $1}' |\
              fzfCmd
          fi
        else
          echo "Nothing was trashed from here."
        fi
      else
        cat "$TRASH_DIR/record" |\
          awk -F ":::" '{print $1}' |\
          fzfCmd
      fi
    else
      echo "There is nothing in the trash."
    fi
    ;;

  "restore")
  ;;
esac
